### PR TITLE
Chisq residuals

### PR DESCRIPTION
**Pull request by rhinopotamus**
Ok, here's a first shot at bonus content about residuals in the chi-square modules. 

I'm really diffident about doing it in 18, because the test in 18 came up non-significant. I tried to express my diffidence in a "word of caution" but idk if it's a good idea.

### CODE REVIEW

**Comment by VectorPosse** [comment]
Yeah, if the test is non-significant, there's not much point checking the
residuals. In fact, it could be problematic to check the residuals, like
seeing patterns that aren't really "there". By the same token, students
should know what to do or not do when tests come back significant or not.
So, yeah, I feel you there.

**Comment by rhinopotamus** [comment]
There's a [nice example in the IMS book](https://openintro-ims.netlify.app/inference-tables.html#tab:diabetes2ExpMetRosiLifestyleSummary) that looks at the efficacy of diabetes treatments. 

Wouldn't be super hard to swap in `(tabyl(diabetes2, treatment, outcome) %>% chisq.test())$residuals` here, if we're interested.

**Comment by VectorPosse** [comment]
I'm cool with that.

**Comment by rhinopotamus** [comment]
Ok. Beep boop, new push coming soon.

**Comment by rhinopotamus** [comment]
I feel better about this.

**Pull request merged**
