### PR TITLE
Remove eugenecist data from Galton

### PR DESCRIPTION
**Pull request by rhinopotamus**
Galton was the founder of the eugenics movement. R module 18 has students use a dataset from Galton's studies on the heritability of physical traits, which he conducted in service of his eugenecist ideals. To avoid giving further credence to racism and eugenics, I suggest we replace this data (and also data collected or used by Fisher, which I'll be looking for) with data that is at least more innocuous.

### CODE REVIEW

**Comment by VectorPosse** [comment]
Yeah, that's fair. (Unfortunate, because good paired data examples are so
hard to find!) It's the standard conundrum of using/studying the work of
flawed individuals from the past. For example, if we threw out everything
in statistics that was discovered by Galton or Fisher, we literally
wouldn't have a stats class left to teach. But, sure, swapping out data
sets seems like a relatively simple fix so as not to promote, even
incidentally, some truly horrible ideas.

**Comment by VectorPosse** [comment]
Oh, I didn't notice that this was a pull request and that you already found
a replacement data set. Even better! Thanks!

**Comment by VectorPosse** [comment]
I'm intrigued by the abstract. If you have a PDF copy, I'd love to read it.
Yes, I totally agree that the data sets we choose could do a much better
job being relevant to social justice issues. Any help you can provide
finding better data is welcome!

**Comment by rhinopotamus** [comment]
I've attached the pdf here -- let me know if no dice.
[Equity_inclusion_and_antiblackness_in_ma.pdf](https://github.com/VectorPosse/Intro_Stats/files/4731530/Equity_inclusion_and_antiblackness_in_ma.pdf)

I also want to render something from the subtext of the previous comment into text: About the problem of finding good data, I think it's not so much that it's hard as it is that we just haven't felt the need to do it. 
Like, once I said to myself, dang, maybe we shouldn't use Galton's data, it took me like half an hour of thinking about other data sets that are already in the modules to think of one that probably had good paired data in it. You know?

So that's kind of my self-assigned project (made slightly more urgent by the fact that I'm teaching DATA 220 as a LC paired with Connie Etter's "imaging justice" class) for this summer: I'm going to be combing through this [list of R datasets](https://vincentarelbundock.github.io/Rdatasets/datasets.html) looking for stuff with more of a justice focus.
Shall I send more pull requests along these lines?

**Comment by VectorPosse** [comment]
Thanks for sending the PDF!

I think when I talk about how difficult it is to find data, it's more than
just combing through the R datasets or importing a file found on the
internet that is thematically interesting. (And I think you might be
surprised once you start looking how truly challenging that can be. It is
true that I have been less motivated to find replacement data sets, but
only because it took me so long to find ones that worked the first time
through!) Data also has to be formatted correctly (DATA 220 is probably not
the place to be doing too much serious data cleaning/reshaping), meet basic
inferential assumptions, and has to elicit pedagogically important ideas.
On that last point, you'll note that along the way, there are data sets
that have, for example, interesting outliers that have to be addressed.
Sometimes, we have a large-ish data set that produces a statistically
significant result even though it's not practically significant. There has
to be a mix of results that reject the null and fail to reject the null. No
single data set has to do all these things, but somewhere in the course in
some data set these ideas have to come up. So there's a bit of a balancing
act...subbing out one data set that has a interesting pedagogical side
effect is fine as long as some other data set in another module also has
that side effect. I should probably have a more comprehensive list of these
learning goals available somewhere.

Anyway, you are totally correct that we can do better, and, data that
speaks to the current issues in the world also has pedagogically important
side effects that are missing in the current curriculum. So I welcome your
help any way you are willing to provide it. Pull requests are great, but
I'm also okay with suggestions posted to the issues area in Github.

Thanks for being so engaged with the modules. With Brian Avery gone, you're
my only hope!  :-)

**Comment by rhinopotamus** [comment]
I appreciate this careful framing of the problem in terms of what makes a good data set. Let us also add to this list of desiderata some ethical considerations around the source / purpose / etc. of this data.

**Comment by VectorPosse** [comment]
I absolutely agree! Thanks again!

**Comment by nerdcommander** [comment]
Haha, without brian *complaining* all the time... ;-) 
Definitely a worthwhile issue to get on top of. The race variables and crime datasets could go away with Galton. 
I made a bunch of supplementary activities last year and used a lot of biomedical data (my bias for sure). Several of them required read.csv and it wasn't too bad. I'm happy to zip up all those activities and data and send them.
The data is very much not perfect and some has race variables in it. 
Thanks for pushing this forward y'all.

**Comment by VectorPosse** [comment]
I'm interested in everyone's opinion about race variables. Any data set
with any kind of demographic data will generally have a race variable,
albeit very poorly conceived and coded. On one hand, this is a teachable
moment, and I've generally used a race variable very early on in the course
(the birthwt data) to discuss how problematic that variable is. But I also
don't want to introduce the epistemological violence that Spencer alludes
to from the Martin paper. So where do we feel like the line is around
removing problematic data, but then at the same time running the danger of
pretending that it doesn't exist. I'm open to ideas here.

**Comment by bbynum** [comment]
Just a general comment. I'm not saying to always "teach the controversy" but I do think that there are multiple paradigms to be explored. Rather than always deplatforming every racist (and in a racist society we almost all have at least implicit bias) sometimes it is more empowering and more effective to make the fuckers pay reparations. How can we intentionally use the techniques they helped create for antiracist purposes? That can potentially be more empowering. It is not perfect but it has been possible to use the words of slave-owning founding fathers to fight racism.
________________________________

**Comment by VectorPosse** [comment]
Thank, Bill. As I think about it more, I also realize that it is only
through race/ethnicity data (even if poorly operationalized) that we can
study systemic oppression. We would not know about disparate impact if we
didn't track some information about the race and/or ethnicity of those
victimized by the system. So I'd love for something in DATA 220 to be able
to discuss this in a pedagogically and ethically appropriate way.

**Comment by rhinopotamus** [comment]
This is exactly what I was about to say, Sean. Removing every dataset with a race variable from our study of statistics is a form of colorblind racism. 

I don't think there are easy / algorithmic / clearcut answers to these questions (like, "if a dataset has race variables it is to be removed"), but I think these are the right questions for us to consider. Ultimately, we gotta do our homework, and we gotta look at our stuff through a lens of, "does this dataset promote antiblack racism."

Here's an article I just googled up that I'll be reading and pondering more: bit.ly/2Hv94HJ

**Comment by VectorPosse** [comment]
"Does this dataset promote antiblack racism?" I think that's the right
question to ask, but maybe it doesn't go far enough. Case in point, the
Galton data--viewed from the naive perspective of someone who doesn't know
about Galton--appears to be objectively measured heights. Like, I could
argue that I have no reason to distrust that Galton measured a bunch of
heights with some reasonable degree of accuracy. I could argue that this
particular dataset is innocuous because it was collected in service of a
part of Galton's program that wasn't racist. (After all, the heritability
of height is a rather uncontroversial genetic fact.) Now there are
considerations exterior to the Galton data that suggest we shouldn't use
it, but the data itself is a seemingly innocuous set of numbers. I'm not
convinced that analyzing that specific dataset has ever promoted anti-black
racism in any of the students who have worked with it to answer
straightforward questions about paired data.

To be clear, I totally agree with getting rid of the Galton data. I'm just
trying to get a clearer idea of the lenses we are proposing.

**Comment by nerdcommander** [comment]
I agree, glad y'all are thinking about it.
as a point of clarification, the race variables that I specifically disagree with and was thinking about are in datasets that have associations between being not white and things like crime, or low smoking and birth-weight babies, since I feel like (in addition to all the other reasons being discussed) flagrantly promote racist ideas and racism. 
I think others are more subtle, and there is a long history of biometric data being involved in very racist ideas, actions, and policies -- height maybe less so than cranial measurements for example. 
Totally think "Does this dataset promote antiblack racism?" and how do we use our craft for the most good that we can? are good questions.  
My other, older complaint that Sean flagged me for, is that many of the example datasets in R are pointless. I don't mean specifically in Data220, but if I have to use the cars data one more time I might throw up. Using socially relevant data, as discussed above, would also address this.
thanks for the discussion!

**Comment by rhinopotamus** [comment]
Yeah I think it's important to note that we can't even use the question "does this dataset promote antiblack racism" as our algorithmic decider, because algorithmic deciders in this complicated and nuanced field of inquiry simply don't and can't exist.

Here is a thing that I think, as (white) academics, we're at risk of falling into here: we can spend all our time wringing our hands for the next three months over the precise form of words we should use to guide and operationalize our deep and sincere commitment to antiracist pedagogy, and thus spend none of our time actually implementing antiracist pedagogy. 

Let's start instead with the baseline assumption that, as we root through these datasets and throw some of them out, that we will probably make some mistakes, and that is going to be okay, because we can iteratively refine these modules as we grow sensitive to new problems.

**Comment by VectorPosse** [comment]
Yes, I think that's a good way to move forward.

**Pull request merged**
